pipelines:
  - name: varsha_ns
    steps:        
      - name: ns_bash
        type: Bash
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          environmentVariables:
            foo: bar
          integrations:
            - name: varsha_artifactory
          outputResources:
            - name: ns_aql
          inputResources:
            - name: ns_dockerbuild_gitRepo
              trigger: false
            - name: ns_image
        execution:
          onExecute:
            - printenv
           
      - name: ns_build_image
        type: DockerBuild
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.110.173:8081/varsha-test/node
          dockerImageTag: latest
          integrations:
            - name: varsha_artifactory
          inputResources:
            - name: ns_dockerbuild_gitRepo
          inputSteps:
            - name: ns_bash
            
      - name: ns_push_image
        type: PushArtifactoryPackage
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          targetRepo: varsha-test
          integrations:
            - name: varsha_artifactory
          inputSteps:
            - name: ns_build_image

      - name: ns_publish_build
        type: PublishBuildInfo
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          integrations:
            - name: varsha_artifactory
          inputSteps:
            - name: ns_push_image
          outputResources:
            - name: ns_buildInfo
      
      - name: ns_promote_build
        type: PromoteBuild
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          targetRepo: promote_docker_testvarsha
          integrations:
            - name: varsha_artifactory
          inputResources:
            - name: ns_buildInfo
          inputSteps:
            - name: ns_publish_build
          outputResources:
            - name: ns_promotedInfo
      
      - name: ns_new_release_bundle
        type: CreateReleaseBundle
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          releaseBundleName: test_new_releaseb
          releaseBundleVersion: v1.0.0
          dryRun: false
          sign: false
          description: "test description"
          integrations:
            - name: varsha_artifactory
          inputResources:
            - name: ns_promotedInfo
          outputResources:
            - name: ns_releaseBundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points
      
      - name: ns_sign
        type: SignReleaseBundle
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          inputResources:
            - name: ns_releaseBundle
          integrations:
            - name: varsha_artifactory
          outputResources:
            - name: ns_releaseBundle2
            
      - name: ns_distribute
        type: DistributeReleaseBundle
        #execution:
        #  onSuccess:
        #    - echo hi
        configuration:
          affinityGroup: dockergroupU18
          nodePool: varsha_u18
          dryRun: false
          #releaseBundleName: test_release
          #releaseBundleVersion: v1.0.1
          integrations:
            - name: varsha_artifactory
          inputResources:
            - name: ns_distributionRule
            - name: ns_releaseBundle2

#       - name: ns_scan
#         type: XrayScan
#         configuration:
#           affinityGroup: dockergroupU18
#           nodePool: varsha_u18
#           buildName: varsha_jpipes
#           buildNumber: 1
#           integrations:
#             - name: varsha_artifactory
#           inputSteps:
#             - name: ns_sign

resources:

  - name: ns_aql
    type: Aql
    configuration:
      sourceArtifactory: varsha_artifactory
      query: 'items.find({"$and":[{"artifact.module.build.name":{"$eq":"native_pipeline"}},{"artifact.module.build.number":{"$eq":"8"}}]})'     
      #addedProperties:
      #  FOO: "value1a value1b"
      #  BAR: "value2a value2b"
      mappings:
        - name: "a"
          input: "regex"
          output: "$1/$2"
        - name: "b"
          input: "regex"
          output: "$2/$1"
          
  - name: ns_image
    type: Image
    configuration:
      imageName: shippabledocker/sample-node
      registry: varsha_docker
      autoPull: true
      imageTag: latest
      
  - name: ns_dockerbuild_gitRepo
    type: GitRepo
    configuration:
      path: jpline/sample-script
      gitProvider: varsha_github
      
  - name: ns_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: varsha_ns
      buildNumber: 123
  
  - name: ns_promotedInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: promote_docker_testvarsha
      buildNumber: 1
      
  - name: ns_distributionRule
    type: DistributionRule
    configuration:
      sourceArtifactory: varsha_artifactory
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - "CN"
        
  - name: ns_releaseBundle
    type: ReleaseBundle
    configuration:
      sourceArtifactory: varsha_artifactory
      name: test_2
      version: v1.1.3

  - name: ns_releaseBundle2
    type: ReleaseBundle
    configuration:
      sourceArtifactory: varsha_artifactory
      name: test
      version: foo
      isSigned: false
      
  - name: ns_distributionRule2
    type: DistributionRule
    configuration:
      sourceArtifactory: varsha_artifactory
      cityName: "Beng"
      serviceName: "luru"
      siteName: "test"
      countryCodes:
        - "3"
        - "91"
        - "141"
        - "67"
