resources:
  - name: sampleScript_ap
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: varsha_github
      branches:
        only: master*
    version:
      sha: master
  
  - name: file_ap
    type: file
    configuration:
      integrationName: varsha_artifactory
    version:
      pattern: "example-repo-local/"

  - name: buildInfo_ap
    type: buildInfo
    version:
      buildName: $PIPELINE_NAME
      buildNumber: 1 # will be updated to $RUN_NUMBER after we have OUT in publish_ap step
     # targetRepo: test
      
  - name: promoteInfo_ap
    type: buildInfo
    version:
      buildName: promote_bldinfo
      buildNumber: 1  
      
pipelines:
  - name: VarshaTestPipeline
    steps:  
      - name: bash_ap
        type: bash
        requires:
          integrations:
            - varsha_slack 
        execution:
          onExecute:
            - echo "test
            - printenv
          #  - jfrog rt u testjf2.sh varsha-ship 
            - send_notification varsha_slack #--payload "payloadFromStep" --pretext "pretext from step" --text "text from step" --recipient 
          onComplete:
            - echo "Oh Yeah Done affinity group"

      - name: build_ap
        type: build
        configuration:
          affinityGroup: ap
          nodePool: kermit_ubuntu18_pool
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: docker-local.104.196.245.50:12330/test
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        triggeredBy:
          resources:
            - sampleScript_ap
          steps:
            - bash_ap
        requires:
          integrations:
            - varsha_artifactory
          resources:
            - file_ap

      - name: push_ap
        type: push
        configuration:
          affinityGroup: ap
          nodePool: kermit_ubuntu18_pool
        setup:
          push:
            targetRepo: jfrog-support-bundle
        requires:
          integrations:
            - varsha_artifactory
        triggeredBy:
          steps:
            - build_ap
            
      - name: publish_ap
        type: publish
        configuration:
          affinityGroup: ap
          nodePool: kermit_ubuntu18_pool
        requires:
          integrations:
            - varsha_artifactory
        triggeredBy:
          steps:
            - push_ap
        outputResources:
          - buildInfo_ap
      
      - name: promote_ap
        type: promote
        configuration:
          nodePool: kermit_ubuntu18_pool
        setup:
          promote:
            targetRepo: varsha_local_repo    
        requires:
          integrations:
            - varsha_artifactory         
        triggeredBy:
          resources:
            - buildInfo_ap
        outputResources:
          - promoteInfo_ap     
