resources:
  - name: sample_jobQ
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/job_testgit
      branches:
        include: master 
        
pipelines:
  - name: pipelinejob1
    steps:
      - name: test1
        type: Bash
        configuration:
          inputResources:
            - sample_jobQ
          runtime:            
            type: image
            image:
              custom:
                name: drydock/c7cppall
                tag: master
                options: "" 
        execution:
          onExecute: 
             - printenv
             - gcc --version
