pipelines:
  - name: varsha_gitRepo
    steps:
      - name: input_git_bash
        type: Bash
        configuration:
          nodePool: varsha_u18
        execution:
          onExecute:
            - printenv
