pipelines:
  - name: varsha_gitRepo
    steps:
      - name: input_git_bash
        type: Bash
        configuration:
          nodePool: varsha_u16
          integrations:
            - name: varsha_slack
          inputResources:
            - name: ip_gitRepo
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
        execution:
          onExecute:
            - printenv
            - docker images
            - java -version
            - mvn --version
            - ant -version 
            - gradle --version 
          onComplete: 
            - echo "Ah! done"
            - send_notification varsha_slack
            
resources:
  - name: ip_gitRepo
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: jpline/sample-script
      buildOn:
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
