resources:

  - name: samples_gitRepo
    type: GitRepo
    configuration:
      path: jpline/sample-script
      gitProvider: varsha_github

pipelines:
  - name: varsha_2steps
    steps:
      - name: simple_bash
        type: Bash
        configuration:
          inputResources:
            - name: samples_gitRepo
        execution:
          onExecute: 
            - printenv
            
      - name: dep_simple
        type: Bash
        configuration:
          inputSteps:
            - name: simple_bash
        execution:
          onExecute: 
            - printenv
          onComplete: 
            - echo "Ah! done"
